// Ern-OS — High-performance, model-neutral Rust AI agent engine
// Created by @mettamazza (github.com/mettamazza)
// License: MIT
//! Composed network behaviour — all libp2p sub-protocols in one derive.
//!
//! ErnMesh composes five sub-protocols into a single `NetworkBehaviour`:
//!
//! - **Gossipsub**: Pub/sub messaging for ErnChat, ErnieBook, and topic broadcasts.
//!   Uses `MessageAuthenticity::Signed` — every message carries an Ed25519 signature.
//! - **Kademlia**: Distributed hash table for global peer discovery and content routing.
//! - **mDNS**: Zero-config local network peer discovery (same LAN).
//! - **Identify**: Exchanges peer metadata (public key, protocols, agent version).
//! - **Ping**: Periodic connectivity checks and RTT measurement.
//!
//! The composed `MeshBehaviour` is used by the Swarm (in `swarm.rs`) to drive
//! all mesh protocol events through a single event loop.

use libp2p::autonat;
use libp2p::dcutr;
use libp2p::gossipsub;
use libp2p::identify;
use libp2p::kad;
use libp2p::mdns;
use libp2p::ping;
use libp2p::relay;
use libp2p::swarm::NetworkBehaviour;
use libp2p_identity::Keypair;

use anyhow::{Context, Result};

use crate::config::MeshConfig;

/// The composed network behaviour — all mesh sub-protocols unified.
///
/// Events from each sub-protocol are merged into [`MeshBehaviourEvent`]
/// (auto-derived by `#[derive(NetworkBehaviour)]`).
#[derive(NetworkBehaviour)]
#[behaviour(to_swarm = "MeshBehaviourEvent")]
pub struct MeshBehaviour {
    /// Pub/sub messaging — signed messages, topic-based routing.
    pub gossipsub: gossipsub::Behaviour,

    /// Kademlia DHT — global peer discovery and content routing.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,

    /// mDNS — local network peer discovery (zero-config).
    pub mdns: mdns::tokio::Behaviour,

    /// Identify — peer metadata exchange (protocols, agent version).
    pub identify: identify::Behaviour,

    /// Ping — connectivity checks and round-trip time measurement.
    pub ping: ping::Behaviour,

    /// AutoNAT — probes external peers to detect NAT status.
    pub autonat: autonat::Behaviour,

    /// Relay client — accepts connections relayed through a circuit relay.
    pub relay_client: relay::client::Behaviour,

    /// DCUtR — upgrades relayed connections to direct via hole-punching.
    pub dcutr: dcutr::Behaviour,
}

/// Unified event type for all sub-protocols.
///
/// Auto-generated by `#[derive(NetworkBehaviour)]`. Each variant wraps
/// the event type of the corresponding sub-protocol.
#[derive(Debug)]
pub enum MeshBehaviourEvent {
    Gossipsub(gossipsub::Event),
    Kademlia(kad::Event),
    Mdns(mdns::Event),
    Identify(identify::Event),
    Ping(ping::Event),
    Autonat(autonat::Event),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
}

impl From<gossipsub::Event> for MeshBehaviourEvent {
    fn from(e: gossipsub::Event) -> Self {
        MeshBehaviourEvent::Gossipsub(e)
    }
}

impl From<kad::Event> for MeshBehaviourEvent {
    fn from(e: kad::Event) -> Self {
        MeshBehaviourEvent::Kademlia(e)
    }
}

impl From<mdns::Event> for MeshBehaviourEvent {
    fn from(e: mdns::Event) -> Self {
        MeshBehaviourEvent::Mdns(e)
    }
}

impl From<identify::Event> for MeshBehaviourEvent {
    fn from(e: identify::Event) -> Self {
        MeshBehaviourEvent::Identify(e)
    }
}

impl From<ping::Event> for MeshBehaviourEvent {
    fn from(e: ping::Event) -> Self {
        MeshBehaviourEvent::Ping(e)
    }
}

impl From<autonat::Event> for MeshBehaviourEvent {
    fn from(e: autonat::Event) -> Self {
        MeshBehaviourEvent::Autonat(e)
    }
}

impl From<relay::client::Event> for MeshBehaviourEvent {
    fn from(e: relay::client::Event) -> Self {
        MeshBehaviourEvent::RelayClient(e)
    }
}

impl From<dcutr::Event> for MeshBehaviourEvent {
    fn from(e: dcutr::Event) -> Self {
        MeshBehaviourEvent::Dcutr(e)
    }
}

/// Build the composed `MeshBehaviour` from config and keypair.
///
/// Configures all five sub-protocols:
/// - Gossipsub with signed message authentication and strict validation
/// - Kademlia with the ErnMesh protocol name
/// - mDNS for LAN discovery
/// - Identify with ErnMesh agent version
/// - Ping with default settings
/// Build the composed behaviour with a relay client from SwarmBuilder.
///
/// The `relay_client` is constructed by SwarmBuilder when `.with_relay_client()`
/// is called, and passed into this function via the behaviour closure.
pub fn build_behaviour_with_relay(
    keypair: &Keypair,
    config: &MeshConfig,
    relay_client: relay::client::Behaviour,
) -> Result<MeshBehaviour> {
    let local_peer_id = libp2p_identity::PeerId::from_public_key(&keypair.public());

    let gossipsub = build_gossipsub(keypair, config)?;
    let kademlia = build_kademlia(local_peer_id)?;

    let mdns = mdns::tokio::Behaviour::new(
        mdns::Config::default(),
        local_peer_id,
    ).context("Failed to create mDNS behaviour")?;

    let identify = identify::Behaviour::new(
        identify::Config::new(
            "/ernmesh/id/1.0.0".to_string(),
            keypair.public(),
        )
        .with_agent_version(format!("ern-mesh/{}", env!("CARGO_PKG_VERSION"))),
    );

    let ping = ping::Behaviour::new(ping::Config::new());

    // ── AutoNAT — probe external peers to detect if we're behind NAT ──
    let autonat = autonat::Behaviour::new(
        local_peer_id,
        autonat::Config::default(),
    );
    tracing::debug!("AutoNAT behaviour configured");

    // ── DCUtR — hole-punching for direct connections through relay ──
    let dcutr = dcutr::Behaviour::new(local_peer_id);
    tracing::debug!("DCUtR behaviour configured");

    tracing::info!(
        peer_id = %local_peer_id,
        "Composed MeshBehaviour: Gossipsub + Kademlia + mDNS + Identify + Ping + AutoNAT + Relay + DCUtR"
    );

    Ok(MeshBehaviour {
        gossipsub,
        kademlia,
        mdns,
        identify,
        ping,
        autonat,
        relay_client,
        dcutr,
    })
}

/// Build Gossipsub with strict configuration per §14.3.
///
/// - `MessageAuthenticity::Signed`: every message carries Ed25519 signature
/// - Message validation enabled
/// - Max transmit size from security config
fn build_gossipsub(
    keypair: &Keypair,
    config: &MeshConfig,
) -> Result<gossipsub::Behaviour> {
    let gossipsub_config = gossipsub::ConfigBuilder::default()
        .max_transmit_size(config.security.max_payload_bytes as usize)
        .validation_mode(gossipsub::ValidationMode::Strict)
        .build()
        .map_err(|e| anyhow::anyhow!("Failed to build Gossipsub config: {}", e))?;

    let gossipsub = gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(keypair.clone()),
        gossipsub_config,
    ).map_err(|e| anyhow::anyhow!("Failed to create Gossipsub behaviour: {}", e))?;

    tracing::debug!(
        max_transmit_size = config.security.max_payload_bytes,
        validation = "strict",
        authentication = "signed",
        "Gossipsub behaviour configured"
    );

    Ok(gossipsub)
}

/// Build Kademlia with ErnMesh protocol name.
fn build_kademlia(
    local_peer_id: libp2p_identity::PeerId,
) -> Result<kad::Behaviour<kad::store::MemoryStore>> {
    let store = kad::store::MemoryStore::new(local_peer_id);
    let mut kademlia = kad::Behaviour::new(local_peer_id, store);

    // Set the Kademlia protocol name to isolate ErnMesh from other networks
    kademlia.set_mode(Some(kad::Mode::Server));

    tracing::debug!(
        protocol = "/ernmesh/kad/1.0.0",
        mode = "server",
        "Kademlia behaviour configured"
    );

    Ok(kademlia)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_keypair() -> Keypair {
        Keypair::generate_ed25519()
    }

    fn test_config() -> MeshConfig {
        let toml = r#"
[mesh]
enabled = true
listen_port = 4001
max_connections = 128
share_bandwidth = true
share_storage_gb = 50

[mesh.economy]
points_per_mb_relayed = 1.0
points_per_gb_hour_stored = 0.5
points_per_1k_tokens_computed = 2.0
points_per_mb_wifi_shared = 0.1
points_per_hour_uptime = 1.0
chunk_size_bytes = 262144
cost_per_1k_tokens_inference = 5.0
cost_per_gb_month_storage = 10.0
cost_per_session_priority = 2.0
cost_per_replica_month = 3.0

[mesh.security]
gossip_score_threshold = -100.0
gossip_graylist_threshold = -1000.0
gossip_score_retention_secs = 3600
max_peers_per_ip = 3
max_peers_per_subnet = 10
max_inbound_connections = 128
max_outbound_connections = 128
max_messages_per_peer_per_sec = 50
max_payload_bytes = 1048576
max_pending_requests_per_peer = 10

[mesh.sharing]
enabled = false
mode = "request-approval"
max_bandwidth_per_peer_mbps = 10
max_concurrent_peers = 5
session_timeout_hours = 24
        "#;
        crate::config::parse_mesh_config(toml).unwrap()
    }

    #[test]
    fn test_build_sub_behaviours_succeed() {
        // build_behaviour_with_relay requires a relay::client::Behaviour from
        // SwarmBuilder — tested via integration test. Here we verify each
        // sub-behaviour builds independently.
        let kp = test_keypair();
        let config = test_config();
        assert!(build_gossipsub(&kp, &config).is_ok(), "Gossipsub must build");
        let pid = libp2p_identity::PeerId::from_public_key(&kp.public());
        assert!(build_kademlia(pid).is_ok(), "Kademlia must build");
    }

    #[test]
    fn test_build_gossipsub_uses_signed_auth() {
        let kp = test_keypair();
        let config = test_config();
        let gs = build_gossipsub(&kp, &config);
        assert!(gs.is_ok(), "Must build Gossipsub with signed auth");
    }

    #[test]
    fn test_build_kademlia_succeeds() {
        let kp = test_keypair();
        let peer_id = libp2p_identity::PeerId::from_public_key(&kp.public());
        let kad = build_kademlia(peer_id);
        assert!(kad.is_ok(), "Must build Kademlia");
    }

    #[test]
    fn test_behaviour_event_from_gossipsub() {
        // Verify the From impl compiles and works
        let _: MeshBehaviourEvent = MeshBehaviourEvent::Gossipsub(
            gossipsub::Event::Subscribed {
                peer_id: libp2p_identity::PeerId::random(),
                topic: gossipsub::TopicHash::from_raw("test"),
            },
        );
    }

    #[test]
    fn test_behaviour_event_from_ping() {
        // Verify the From impl compiles
        let event = ping::Event {
            peer: libp2p_identity::PeerId::random(),
            result: Ok(std::time::Duration::from_millis(42)),
            connection: libp2p::swarm::ConnectionId::new_unchecked(0),
        };
        let _mesh_event: MeshBehaviourEvent = event.into();
    }
}
